categories = [
  "Add",
  "Adjust",
  "Document",
  "Extract",
  "Fix",
  "Generalize",
  "Make",
  "Migrate",
  "Recategorize",
  "Refactor",
  "Re-integrate",
  "Remove",
  "Reorganize",
  "Rename",
  "Resize",
  "Throw",
  "Update"
]
category_delimiters = ["", ""]
colored_output = false
enable_debug = true
excluded_commit_tags = []
enable_footers = true
show_commit_hash = true
show_prefix = false
sort_by = "date"
template_prefix = ""
